language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "masikisiki-github"
    token:
      secure: ${SONAR_TOKEN}
before_install:
  - chmod +x mvnw
script: ./mvnw clean verify sonar:sonar
