language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "masikisiki_katas"
#    token:
#      secure: ${SONAR_TOKEN}
before_install:
  - chmod +x mvnw
script: ./mvnw clean verify sonar:sonar -Dsonar.login=${SONAR_TOKEN}
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
